config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :expenses
  resources :groups
  devise_for :users
  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  authenticated :user do
    root 'groups#index', as: :authenticated_root
  end
  unauthenticated :user do
    root 'users#splash', as: :unauthenticated_root
  end
end

app/models/ability.rb
# frozen_string_literal: true

# Ability class for authorization
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    return unless user.id

    can :manage, Group, user_id: user.id
    can :manage, Expense, author_id: user.id
  end
end

app/models/application_record.rb
# frozen_string_literal: true

# Application record
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
# frozen_string_literal: true

# Expense model
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :groups

  validates :name, presence: true, length: { minimum: 3, maximum: 100 }
  validates :amount, numericality: { greater_than: 0 }
end

app/models/group.rb
# frozen_string_literal: true

# Group model
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :expenses
  has_one_attached :icon

  validates :name, presence: true, length: { minimum: 3, maximum: 100 }
  validates :icon, presence: true

  def total_expense
    expenses.sum(:amount) || 0
  end
end

app/models/user.rb
# frozen_string_literal: true

# User model
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :expenses, foreign_key: 'author_id'
  has_many :groups

  validates :name, presence: true, length: { minimum: 3, maximum: 20 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# base class for all controllers
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/expenses_controller.rb
# frozen_string_literal: true

# Path: app\controllers\expenses_controller.rb
class ExpensesController < ApplicationController
  load_and_authorize_resource

  # GET /expenses or /expenses.json
  def index
    @expenses = Expense.all
  end

  # GET /expenses/1 or /expenses/1.json
  def show; end

  # GET /expenses/new
  def new
    @expense = Expense.new
    @group = Group.find(params[:group_id]) if params[:group_id].present?
  end

  # GET /expenses/1/edit
  def edit; end

  # POST /expenses or /expenses.json
  def create
    @expense = build_expense
    @group = Group.find(params[:expense][:group_id])
    @group.expenses << @expense
    respond_to do |format|
      if @expense.save
        format.html { redirect_to @group, notice: 'Expense was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to expense_url(@expense), notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy
    @group = Group.find(params[:group_id])

    respond_to do |format|
      format.html { redirect_to @group, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_expense
    @expense = Expense.find(params[:id])
  end

  def build_expense
    expense = Expense.new(expense_params)
    expense.author = current_user
    expense
  end

  # Only allow a list of trusted parameters through.
  def expense_params
    params.require(:expense).permit(:name, :amount)
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

# grab controller from app\controllers\groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource

  # GET /groups or /groups.json
  def index
    @groups = Group.accessible_by(current_ability).all.order(created_at: :desc).includes(icon_attachment: :blob)
  end

  # GET /groups/1 or /groups/1.json
  def show
    @expenses = @group.expenses.order(created_at: :desc)
    @title = 'Transactions'
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)
    @group.user = current_user
    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Group was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to authenticated_root_path, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :user_id, :icon)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Path: app\controllers\users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: :splash
  def splash; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Path: app\helpers\application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
# frozen_string_literal: true

# Path: app\controllers\expenses_controller.rb
module ExpensesHelper
end

app/helpers/groups_helper.rb
# frozen_string_literal: true

# Path: app\controllers\expenses_controller.rb
module GroupsHelper
end

app/views/expenses/new.html.erb
<nav class="w-full flex justify-between items-center bg-AppBlue text-white h-10 px-3">
  <%= link_to @group do %>
    <i class="fa fa-arrow-left link-hover"></i>
  <% end %>
  <h1 class='font-ProximaBold font-medium'>Nouvelle Dépense</h1>
  <i class="fa fa-searc link-hover"></i>
</nav><br/>

<div class="flex flex-col pl-3">
  <%= form_with(model: @expense) do |form| %>
    <div class="field w-full">
      <%= form.text_field :name, placeholder: "Detail" %>
    </div>
    <div class="field w-full">
      <%= form.number_field :amount,placeholder: "Montant"  %>
    </div>
    <%= form.hidden_field :group_id, value: @group.id %>
    <div class="submit w-full flex justify-center items-center py-3 px-6 font-ProximaBold">
      <%= form.submit %>
    </div>
    <% if @expense.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(expense.errors.count, "error") %> Dépense non enregistrable:</h2>
        <ul>
          <% expense.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>
</div>

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>

  <div class="flex flex-col p-3 bg-white w-3/4 text-black new-cat ">
    <%= form.label :icon %>
    <%= form.file_field :icon, accept:"image/png, image/gif, image/jpeg, image/svg, image/jpg" %>
  </div><br/>

  <div class="field new-category" style="display: block">
    <%= form.text_field :name, placeholder:"Titre" %>
  </div>

  <br/>
  <div class="submit flex justify-center items-center py-3 px-6 font-ProximaBold">
    <%= form.submit %>
  </div>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> Non enregistrable:</h2>
      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>"
     class="group group/item hover:bg-slate-100
     bg-AppWhite mb-4 rounded px-3 py-3 flex
     justify-between items-center">
  <div class="flex space-x-5 items-center">
    <% if group.icon.attached? %>
      <div class="h-20 w-14">
        <img src="<%= url_for(group.icon) %>" alt="img" class="object-cover h-full w-full rounded-md">
      </div>
    <% end %>
    <div class="flex flex-col h-full space-y-5">
      <p class="text-AppGrayDark font-bold"><%= group.name %></p>
      <p class="text-xs text-AppGray font-normal"><%= group.created_at.strftime('%d %B %Y') %></p>
    </div>
  </div>
  <div class="flex flex-col h-full space-y-5">
    <p class="text-AppGrayDark font-bold text-xl">$<%= group.total_expense %></p>
    <div class="bg-[#fd5a5a] text-white rounded-[5px] px-[2px] py-[2px] invisible group-hover/item:visible"><%= button_to "suprimer", group_path(group.id),  method: :delete, data: { turbo_confirm: "Are you sure?" } %></div>
  </div>
</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<section class="bg-AppGrayLight h-full flex flex-col items-center">
  <nav class="w-full flex justify-between items-center field
  bg-AppBlue text-white h-10 px-3">
    <i class="fa fa-bars link-hover peer nav-toggle hamburger" id= "hamburger"></i>
    <div class="hidden bg-AppWhite text-xl absolute top-0 left-0
    right-0 h-[45px] justify-between
    items-center px-[10px] py-[7px] peer-[.nav-toggle] nav-pop">
      <h1 class="text-AppGrayDark font-bold"><%= current_user.name %></h1>
      <%= link_to "logout", logout_path %>
      <svg xmlns="http://www.w3.org/2000/svg" class="close" height="2em" viewBox="0 0 384 512">
        <style>svg{fill:#f00a2c}</style><path d="M342.6 150.6c12.5-12.5 12.5-32.8
      0-45.3s-32.8-12.5-45.3 0L192 210.7 86.6 105.4c-12.5-12.5-32.8-12.5-45.3
      0s-12.5 32.8 0 45.3L146.7 256 41.4 361.4c-12.5 12.5-12.5 32.8 0 45.3s32.8
      12.5 45.3 0L192 301.3 297.4 406.6c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8
      0-45.3L237.3 256 342.6 150.6z"/></svg>
    </div>
    <h1 class='font-ProximaBold font-medium'>Mes Categories</h1>
    <i class="fa fa-search link-hover"></i>
  </nav>
  <div class="bg-AppBlue w-full flex justify-between items-center px-1.5 py-1.5 ">
    <p class="text-white"> <%= link_to 'Sortir', logout_path %> </p>
    <p class="text-white font-ProximaLight">Plus Recent</p>
    <p class="text-AppGrayDark font-normal">Plus ancien</p>
  </div>
  <div class="w-full bg-AppWhite border-transparent flex justify-between items-center gift h-12 ">
    <p class="text-AppGrayLight font-ProximaLight text-lg">Gift Card</p>
    <p class="font-bold text-black gift-price  text-lg">$45.00</p>
  </div>
  <br/>

  <div id="groups" class="groups w-full flex flex-col items-center">
    <% @groups.each do |group| %>
      <%= link_to group do %>
        <%= render group %>
       <% end %>
    <% end %>
  </div>

  <div class="foot w-full absolute bottom-0 bg-AppGreen flex justify-center items-center px-2">
    <%= link_to "Ajouter categorie", new_group_path %>
  </div>
</section>

app/views/groups/new.html.erb
<section class="bg-AppGrayLight h-full flex flex-col items-center">
  <nav class="w-full flex justify-between items-center bg-AppBlue text-white h-10 px-3">
    <%= link_to groups_path do %>
      <i class="fa fa-arrow-left link-hover"></i>
    <% end %>
    <h1 class='font-ProximaBold font-medium'>Nouvelle Categorie</h1>
    <i class="fa fa-searc link-hover"></i>
  </nav><br/>
  <div class="w-full px-2">
    <%= render "form", group: @group %>
  </div>
<br>
</section>

app/views/groups/show.html.erb
<section class="bg-AppGrayLight h-full flex flex-col items-center">
  <nav class="w-full flex justify-between items-center bg-AppBlue text-white h-10 px-3">
    <%= link_to groups_path do %>
      <i class="fa fa-arrow-left link-hover"></i>
    <% end %>
    <h1 class='font-ProximaBold font-medium'>Mes Dépenses</h1>
    <i class="fa fa-searc link-hover"></i>
  </nav>
  <div class="bg-AppWhite flex flex-col mt-2 rounded-md details">
    <%= render @group %>
    <hr style="height: 2px; width: 90%; ">
    <div id="expenses">
      <% if @expenses.any? %>
        <% @expenses.each do |expense| %>
          <div class="flex flex-col space-y-5 mt-4 px-[3px] py-[3] group/item hover:bg-slate-100 ">
            <div class="flex justify-between items-center text-AppGrayDark font-medium">
              <p><%= expense.name %></p>
              <p>$<%= expense.amount %></p>
            </div>
            <div class="flex justify-between items-center">
              <p class="text-AppGrayLight font-medium text-sm"><%= expense.created_at %></p>
              <div class="bg-[#fd5a5a] text-white rounded-[5px]
              px-[2px] py-[2px] invisible group-hover/item:visible">
                <%= button_to "enlever", expense, method: :delete, params: { group_id: @group.id } %>
              </div>
            </div>
          </div>
          <hr style="margin: 7px 0">
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="foot w-full absolute bottom-0 bg-AppGreen flex justify-center items-center px-2">
    <%= link_to "Ajouter dépense", new_expense_path(group_id: @group.id) %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBudget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags('nav-toggle.js') %>
  </head>

  <body>
  <%= yield %>
  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="w-full flex justify-between items-center bg-AppBlue text-white h-10 px-3">
  <%= link_to groups_path do %>
    <i class="fa fa-arrow-left link-hover"></i>
  <% end %>
  <h1 class='font-ProximaBold font-medium'>Transactions</h1>
  <i class="fa fa-searc link-hover"></i>
</nav>

app/views/users/splash.html.erb
<section
  id="splash"
  class="w-full h-[500px] max-h-screen flex flex-col justify-between items-center bg-AppWhite "
>
  <h1 class="text-4xl font-ProximaBold text-center mt-[150px] text-AppGrayDark mb-6"
      style="font-size: 27px">
     Budget Tracker
  </h1>
  <div class="flex flex-col items-center w-full space-y-5 ">
    <%= link_to "Se Connecté", new_user_session_path,
                class:"flex items-center justify-center
                bg-AppBlue w-4/5 h-12 text-white
                font-ProximaLight text-center
                sm:max-w-sm button-hover" %>
     <%= link_to "Creer un Compte", new_user_registration_path,
                 class:"flex items-center
                  justify-center bg-AppGray
                  w-4/5 h-12 text-AppGray
                  font-ProximaLight text-center
                  sm:max-w-sm button-hover border mt-0" %>
  </div>
</section>